[env:genericSTM32F103C6]
platform = ststm32
board = genericSTM32F103C6
framework = arduino
upload_protocol = stlink ; Sử dụng mạch nạp ST-Link
monitor_speed = 115200

; Tối ưu bộ nhớ cho chip C6 (32KB Flash)
build_flags = 
    -D SERIAL_UART_INSTANCE=1
    -D PIN_SERIAL_TX=PA9
    -D PIN_SERIAL_RX=PA10
    
